-- =============================================================================
-- 00_ROLES_AND_ACCESS
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Functional Security Roles
CREATE OR REPLACE ROLE SECURELIFE_DATA_ENGINEER;
CREATE OR REPLACE ROLE SECURELIFE_DS_ANALYST;
CREATE OR REPLACE ROLE SECURELIFE_COMPLIANCE_OFFICER;

-- Grant to hierarchy
GRANT ROLE SECURELIFE_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE SECURELIFE_DS_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SECURELIFE_COMPLIANCE_OFFICER TO ROLE SYSADMIN;

-- Object Privileges
GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DATA_ENGINEER;

GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DS_ANALYST;
GRANT USAGE ON SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_DS_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_DS_ANALYST;

GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_COMPLIANCE_OFFICER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SECURELIFE_DB TO ROLE SECURELIFE_COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN DATABASE SECURELIFE_DB TO ROLE SECURELIFE_COMPLIANCE_OFFICER;
