-- =============================================================================
-- 01_MASKING_POLICIES
-- =============================================================================

USE SCHEMA SECURELIFE_DB.GOVERNANCE;

-- National Insurance Number Masking
CREATE OR REPLACE MASKING POLICY MSK_NINO
AS (VAL VARCHAR) RETURNS varchar ->
    CASE
        WHEN CURRENT_ROLE() IN ('SECURELIFE_ADMIN', 'SECURELIFE_COMPLIANCE_OFFICER') THEN VAL
        ELSE SUBSTR(VAL, 1, 2) || ' **** ' || SUBSTR(VAL, 8, 2)
    END;

-- Email Masking for Analysts
CREATE OR REPLACE MASKING POLICY MSK_EMAIL
AS (VAL VARCHAR) RETURNS varchar ->
    CASE
        WHEN CURRENT_ROLE() IN ('SECURELIFE_ADMIN', 'SECURELIFE_COMPLIANCE_OFFICER') THEN VAL
        ELSE REGEXP_REPLACE(VAL, '^(.).*(.@.*)$', '\\1***\\2')
    END;

-- Apply to Domain Tables
ALTER TABLE SECURELIFE_DB.DOMAIN.DIM_CUSTOMER
MODIFY COLUMN NATIONAL_INSURANCE_NUMBER SET MASKING POLICY MSK_NINO;

ALTER TABLE SECURELIFE_DB.DOMAIN.DIM_CUSTOMER
MODIFY COLUMN EMAIL_ADDRESS SET MASKING POLICY MSK_EMAIL;
