-- =============================================================================
-- VW_ODS_POLICIES
-- =============================================================================

USE SCHEMA SECURELIFE_DB.ODS;

CREATE OR REPLACE VIEW VW_ODS_POLICIES AS
WITH UNIFIED_POLICIES AS (
    SELECT
        POLICY_ID AS POLICY_REF,
'LEGACY_MOTOR' AS SOURCE_SYSTEM,
HOLDER_NAME AS CUSTOMER_ID_REF,
        ADDRESS_POSTCODE AS POSTCODE,
ANNUAL_PREMIUM AS PREMIUM_AMOUNT,
RENEWAL_DATE,
'MOTOR' AS PRODUCT_LINE,
        METADATA$TS AS EXTRACT_TS
    FROM SECURELIFE_DB.STAGING.STRM_MOTOR_POLICY
    WHERE METADATA$ACTION = 'INSERT'

    UNION ALL

    SELECT
        POLICY_REF,
'LEGACY_HOME',
CUSTOMER_EMAIL,
        POSTCODE,
TOTAL_PREMIUM,
NULL,
'HOME',
        METADATA$TS
    FROM SECURELIFE_DB.STAGING.STRM_HOME_POLICY
    WHERE METADATA$ACTION = 'INSERT'

    UNION ALL

    SELECT
        TRANS_ID,
'LEGACY_LIFE',
NATIONAL_INS_NUM,
        NULL,
MONTHLY_PREMIUM * 12,
NULL,
'LIFE',
        METADATA$TS
    FROM SECURELIFE_DB.STAGING.STRM_LIFE_POLICY
    WHERE METADATA$ACTION = 'INSERT'
)

SELECT * FROM UNIFIED_POLICIES
QUALIFY ROW_NUMBER() OVER (PARTITION BY POLICY_REF ORDER BY EXTRACT_TS DESC) = 1;
