-- =============================================================================
-- VW_CUSTOMER_360
-- =============================================================================

USE SCHEMA SECURELIFE_DB.DOMAIN;

CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
WITH CUSTOMER_BASE AS (
    SELECT
        CUSTOMER_KEY,
        GLOBAL_CUSTOMER_ID,
        POSTCODE,
        LOYALTY_TIER,
        MARKETING_CONSENT_FLAG,
        VULNERABLE_CUSTOMER_FLAG,
        SOURCE_SYSTEMS,
        FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME
    FROM DIM_CUSTOMER
    WHERE IS_CURRENT = TRUE
),

POLICY_SUMMARY AS (
    SELECT
        CUSTOMER_KEY,
        COUNT(DISTINCT POLICY_TYPE_KEY) AS UNIQUE_PRODUCT_LINES,
        COUNT(CASE WHEN IS_ACTIVE = TRUE THEN 1 END) AS ACTIVE_POLICIES_COUNT,
        SUM(CASE WHEN IS_ACTIVE = TRUE THEN TOTAL_WRITTEN_PREMIUM ELSE 0 END) AS TOTAL_ANNUALISED_PREMIUM_GBP,
        MIN(EXPIRY_DATE_KEY) AS NEXT_RENEWAL_DATE_KEY
    FROM FCT_POLICY_SALES
    GROUP BY CUSTOMER_KEY
),

CLAIMS_SUMMARY AS (
    SELECT
        CUSTOMER_KEY,
        COUNT(*) AS TOTAL_CLAIMS_COUNT,
        SUM(PAID_OUT_AMOUNT_GBP) AS TOTAL_PAID_OUT_GBP,
        MAX(CASE WHEN IS_AT_FAULT_CLAIM = TRUE THEN 1 ELSE 0 END) AS HAD_AT_FAULT_CLAIM_FLAG
    FROM FCT_CLAIMS
    GROUP BY CUSTOMER_KEY
)

SELECT
    C.GLOBAL_CUSTOMER_ID,
    C.FULL_NAME,
    C.POSTCODE,
    C.LOYALTY_TIER,
    C.MARKETING_CONSENT_FLAG,
    C.VULNERABLE_CUSTOMER_FLAG,
    C.SOURCE_SYSTEMS AS CONTRIBUTING_SOURCES,
    COALESCE(P.ACTIVE_POLICIES_COUNT, 0) AS ACTIVE_POLICIES,
    COALESCE(P.UNIQUE_PRODUCT_LINES, 0) AS PRODUCT_DENSITY,
    COALESCE(P.TOTAL_ANNUALISED_PREMIUM_GBP, 0) AS TOTAL_CUSTOMER_VALUE_GBP,
    COALESCE(CL.TOTAL_CLAIMS_COUNT, 0) AS LIFETIME_CLAIMS,
    ROUND(COALESCE(CL.TOTAL_PAID_OUT_GBP, 0) / NULLIF(P.TOTAL_ANNUALISED_PREMIUM_GBP, 0), 2) AS LOSS_RATIO
FROM CUSTOMER_BASE AS C
LEFT JOIN POLICY_SUMMARY AS P ON C.CUSTOMER_KEY = P.CUSTOMER_KEY
LEFT JOIN CLAIMS_SUMMARY AS CL ON C.CUSTOMER_KEY = CL.CUSTOMER_KEY;
