-- =============================================================================
-- DIM_CUSTOMER (SCD Type 2)
-- =============================================================================

USE SCHEMA SECURELIFE_DB.DOMAIN;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER IDENTITY (1, 1) PRIMARY KEY,
    GLOBAL_CUSTOMER_ID VARCHAR(50) NOT NULL,

    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    NATIONAL_INSURANCE_NUMBER VARCHAR(20),

    EMAIL_ADDRESS VARCHAR(255),
    POSTCODE VARCHAR(10),
    CITY_TOWN VARCHAR(100),

    MARKETING_CONSENT_FLAG BOOLEAN DEFAULT FALSE,
    VULNERABLE_CUSTOMER_FLAG BOOLEAN DEFAULT FALSE,
    LOYALTY_TIER VARCHAR(20) DEFAULT 'STANDARD',

    -- SCD Type 2 tracking
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,

    SOURCE_SYSTEMS VARCHAR(255),
    DW_INSERT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MD5_HASH VARCHAR(32) NOT NULL
)
COMMENT = 'SCV Golden Record: Unified view of policyholder with history tracking';
