-- =============================================================================
-- SECURELIFE UK INSURANCE - SYSTEM SETUP
-- =============================================================================
-- Purpose:    Create Database, Schemas, and Role-Based Access Control (RBAC)
-- Author:     Elliott Fairhall
-- UK English: Standardised
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Create Database
CREATE OR REPLACE DATABASE SECURELIFE_DB
COMMENT = 'SecureLife UK Enterprise Data Platform - Single Customer View';

-- 2. Create Medallion Layer Schemas
CREATE OR REPLACE SCHEMA SECURELIFE_DB.STAGING
COMMENT = 'Landing zone for Motor, Home, and Life source system extracts';

CREATE OR REPLACE SCHEMA SECURELIFE_DB.ODS
COMMENT = 'Operational Data Store: Deduplicated and integrated insurance records';

CREATE OR REPLACE SCHEMA SECURELIFE_DB.DOMAIN
COMMENT = 'Dimensional Model: SCV Gold Records, Policy Facts, and Analytical views';

CREATE OR REPLACE SCHEMA SECURELIFE_DB.UTILS
COMMENT = 'Utilities: Logging, metadata tracking, and orchestration procedures';

CREATE OR REPLACE SCHEMA SECURELIFE_DB.GOVERNANCE
COMMENT = 'Governance: Masking policies and row-level security for FCA compliance';

-- 3. Create Warehouse
CREATE OR REPLACE WAREHOUSE SECURELIFE_WH
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'General compute warehouse for SecureLife data processing';

-- 4. Initialise Functional Roles
CREATE OR REPLACE ROLE SECURELIFE_ADMIN;
CREATE OR REPLACE ROLE SECURELIFE_DEVELOPER;
CREATE OR REPLACE ROLE SECURELIFE_ANALYST;
CREATE OR REPLACE ROLE SECURELIFE_COMPLIANCE;

-- Grant permissions to Admin
GRANT ALL PRIVILEGES ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE SECURELIFE_WH TO ROLE SECURELIFE_ADMIN;

-- Grant permissions to Developer (Build access)
GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DEVELOPER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SECURELIFE_DB TO ROLE SECURELIFE_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON SCHEMA SECURELIFE_DB.ODS TO ROLE SECURELIFE_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON SCHEMA SECURELIFE_DB.STAGING TO ROLE SECURELIFE_DEVELOPER;

-- Grant permissions to Analyst (Read-only on Domain)
GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_ANALYST;
GRANT USAGE ON SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_ANALYST;

-- Grant permissions to Compliance (Masked data access)
GRANT USAGE ON DATABASE SECURELIFE_DB TO ROLE SECURELIFE_COMPLIANCE;
GRANT USAGE ON SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_COMPLIANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA SECURELIFE_DB.DOMAIN TO ROLE SECURELIFE_COMPLIANCE;

-- 5. Set default context
USE ROLE SECURELIFE_ADMIN;
USE DATABASE SECURELIFE_DB;
USE SCHEMA UTILS;
